version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.3
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
Branches:
  only: 
     -  main
  # Pull Requests builds so that each time opening a pull request against the main branch, tests and build are executed.
on:
  pull_request:
    branches: [ main ]
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - checkout 
      - node/install
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      # install dependencies in both apps
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
      - run:
          name: EB Create
          command: |
            eb init application-1 --platform node.js --region us-east-1
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
      - run:
          name: Setup Environment Variables
          command: |
            eb setenv FIRST_NAME=Mustafa
